name: SimpleHelpTickets
main: me.odium.simplehelptickets.SimpleHelpTickets
version: 1.3.9
commands:
   sht:
      aliases: [helptickets, simplehelptickets]
      description: Help Menu
      permission:
      usage: /sht
   ticket:
      aliases: [helpme, grief, idea]
      description: Open a help ticket or submit an idea
      permission: sht.ticket
      usage: /ticket <Description>
   tickets:
      aliases: [ideas]
      description: Review your tickets or ideas (or all tickets or ideas)
      permission:
      usage: /tickets [-v|-a|-c]
   closeticket:
      aliases: [closeidea]
      description: close a help ticket or idea (-r <#> to reopen)
      permission:
      usage: /closeticket [-r] <#>
   replyticket:
      aliases: [rticket, replyidea, ridea]
      description: reply to a help ticket or idea
      permission:
      usage: /replyticket <#> <reply>
   taketicket:
      aliases: [takeidea]
      description: Assign self to a help ticket or idea
      permission: sht.admin
      usage: /taketicket <#>
   checkticket:
      aliases: [chticket, checkidea, chidea]
      description: check your help ticket or idea
      permission:
      usage: /checkticket <#>
   delticket:
      aliases: [dticket, delidea]
      description: Delete a ticket or idea
      permission:
      usage: /delticket <#>
   purgetickets:
      aliases: [ptickets, purgeideas]
      description: Purge all expired tickets or ideas
      permission: sht.admin
      usage: /purgetickets
   findtickets:
      aliases: [findideas]
      description: Search for tickets or ideas
      permission:
      usage: /findtickets t:3d text to find  (see full details with /findtickets help)
