name: SimpleHelpTickets
main: me.odium.simplehelptickets.SimpleHelpTickets
version: 0.9
commands:
   sht:
      aliases: [simplehelptickets]
      description: Help Menu
      permission:
      usage: /sht
   ticket:
      aliases: [helpme]
      description: Open a help ticket
      permission: sht.ticket
      usage: /ticket <Description>
   tickets:
      description: Review your/all help tickets
      permission:
      usage: /tickets   
   closeticket:
      description: close your/a help ticket
      permission:
      usage: /closeticket <#>
   replyticket:
      description: reply to a help ticket
      permission: sht.admin
      usage: /replyticket <#> <reply>
   taketicket:
      description: Assign self to a help ticket
      permission: sht.admin
      usage: /taketicket <#>
   checkticket:
      description: check your/a help ticket
      permission:
      usage: /checkticket <#>
   delticket:
      description: Quietly delete a help ticket
      permission:
      usage: /delticket <#>